name: Run Dialyzer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dialyzer:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Dialyzer PLT
      uses: actions/cache@v3
      with:
        path: _build/dialyzer
        key: ${{ runner.os }}-elixir-${{ hashFiles('mix.lock') }}-plt
        restore-keys: |
          ${{ runner.os }}-elixir-plt

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 'latest'
        otp-version: 'latest'

    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix dialyzer --plt

    - name: Run Dialyzer
      run: |
        mix dialyzer --halt-exit-status
