name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 'latest'
        otp-version: 'latest'

    - name: Restore cache
      id: build-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: _build
        key: build-cache-${{ runner.os }}

    - name: Install dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Cache dependencies
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}

    - name: Compile
      run: |
        mix compile

    - name: Cache compiled artifacts
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}

    - name: Test
      env:
        MIX_ENV: test
      run: |
        mix test

    - name: Cache test artifacts
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}

    - name: Dialyzer
      env:
        MIX_ENV: dev
      run: |
        mix deps.get
        mix compile
        mix dialyzer

    - name: Cache dialyzer plts and artifacts
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}
