name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 'latest'
        otp-version: 'latest'

    - name: Cache Build Artifacts
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-elixir-${{ hashFiles('mix.lock') }}-build
        restore-keys: |
          ${{ runner.os }}-elixir-build

    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Run Tests
      run: |
        mix test

    - name: Run Dialyzer
      run: |
        mix dialyzer --halt-exit-status
