name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 'latest'
        otp-version: 'latest'

    - name: Restore Cache
      uses: actions/cache@v4
      with:
        path: _build
        key: build-cache-${{ runner.os }}

    - name: Install dependencies and compile
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix compile

    - name: Run Tests
      env:
        MIX_ENV: test
      run: |
        mix test

    - name: Run Dialyzer
      env:
        MIX_ENV: dev
      run: |
        mix dialyzer
