name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 'latest'
        otp-version: 'latest'

    - name: Restore cache
      id: build-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: _build
        key: build-cache-${{ runner.os }}

    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Cache dependencies
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}

    - name: Compile
      run: |
        MIX_ENV=test mix compile
        MIX_ENV=dev mix compile

    - name: Cache compiled artifacts
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}

    - name: Run tests
      run: MIX_ENV=test mix test

    - name: Run dialyzer
      run: MIX_ENV=dev mix dialyzer

    - name: Cache PLTs
      uses: actions/cache/save@v4
      with:
        path: _build
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}
